services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_app"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fitness-app
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/fitness_app
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
      SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:8080/v3/api-docs
    depends_on:
      - app

volumes:
  postgres-data: